server:
  port: 8091
spring:
  kafka:
    bootstrap-servers: 192.168.148.143:9092,192.168.148.143:9093,192.168.148.143:9094
    consumer:
      group-id: default-group
      # ????
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500
    listener:
      # ??????????????ListenerConsumer???????
      # RECORD
      # ????poll()???????????ListenerConsumer???????
      # BATCH
      # ????poll()???????????ListenerConsumer????????????????TIME???
      # TIME
      # ????poll()???????????ListenerConsumer?????????record??????COUNT???
      # COUNT
      # TIME |?COUNT???????????
      # COUNT_TIME
      # ????poll()???????????ListenerConsumer?????, ????Acknowledgment.acknowledge()???
      # MANUAL
      # ????Acknowledgment.acknowledge()????????????
      # MANUAL_IMMEDIATE
      ack-mode: MANUAL_IMMEDIATE