spring:
  application:
    name: my-redis-demo
    
  redis:
    host: 192.168.148.138
    port: 6379
    password: admin
    jedis:
      pool:
        max-active: 10
        max-idle: 10


server:
  port: 8081
