server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/2021-10-22_vue_springboot
    username: root
    password: root
    type:  com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
