spring:
  cloud:
    config:
      #配置中心地址
      uri: http://localhost:8888
      #配置文件名称
      name: test-consumer
      #配置文件类型
      profile: pre
      #配置文件分支
      label: master
#server:
#  port: 8763
#spring:
#  application:
#    name: user-consumer
#
#eureka:
#  client:
#    service-url: 
#      defalutZone: http://localhost:8761/eureka/