dubbo:
  application:
    name: device-web
  registry:
    address: zookeeper://192.168.148.142:2181

server:
  port: 8090
  
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: device-web
