spring:
  redis:
    host: 192.168.148.138
    port: 6379
    password: admin
    jedis:
      pool:
        max-active: 10
        max-idle: 10
  thymeleaf:
    cache: false
    mode: HTML

server:
  port: 8081
